### ISSUE TITLE
Deprecated FIPS algorithm

### ISSUE THREAD

**Issue by radford-for-smpte** [SMPTE/st429-6#3]
The 2nd paragraph of Section 7.10 describes a process that is now deprecated by FIPS. That is, deriving the `MICKey` from the `CypherKey` is no longer permitted, and devices that perform that derivation will not pass FIPS testing (and by extension, the DCI CTP).

I suggest we eliminate this paragraph and replace it with a note that informs the reader that:

1. In the past, `MICKey` was derived from the `CypheyKey` but that derivation is now forbidden
2. DCI now defines a method to retrieve the `MICKey` from within the KDM along w/ an informative link to [Section 9.4.3.5 Item #6 of the DCI Spec](https://dcss.dcimovies.com/0c0cff34d231b516cb89ae3fad352d5cf37a9515/dcss.html#sec-9-4-3-5)

**Comment by palemieux** [comment]
@radford-for-smpte See https://doc.smpte-doc.org/st429-6-private/main/#sec-mic

**Comment by palemieux** [comment]
Fixed at 48de6a13394355e695d83d17312903804ae0b477
