### ISSUE TITLE
MIC Key Legacy Algorithm Deprecation for SMs Only

### ISSUE THREAD

**Issue by jpviollet** [SMPTE/st429-6#5]
In-line with the ST 429-2 addition proposed at https://github.com/SMPTE/st429-2/issues/13, the following should be changed in ST 429-6 as well:

In Annex B, change:
 
“_This method is no longer considered cryptographically adequate and should not be used. Furthermore, [FIPS PUB 186-2](https://doc.smpte-doc.org/st429-6-private/main/#bib-fips-186-2) has been withdrawn and the method is therefore reproduced below to allow the interpretation of legacy Track Files that used it_.”
 
To:
 
“**_This method is should not be used by Security Managers (SMs)._**”
 
In section 9.1, change:
 
“_Annex B specifies a deprecated method by which the MIC Key is derived from the Cipher Key_. “
 
To:
 
“_**Annex B specifies a deprecated method by which the Security Managers (SMs) derived the MIC Key from the Cipher Key**_.”

**Comment by dcbullock** [comment]
Annex B should be normative.

**Comment by palemieux** [comment]
> “This method is should not be used by Security Managers (SMs).”

ST 429-6 has no concept of SMs, so this document is not the right place for that requirement.

**Comment by palemieux** [comment]
>“Annex B specifies a deprecated method by which the Security Managers (SMs) derived the MIC Key from the Cipher Key.”

I recommend "Annex B specifies a method which is no longer required by the Reference Decryption Processing Model of Clause 11", since ST 429-6 has no concept of SM.

**Comment by dcbullock** [comment]
> > “This method is should not be used by Security Managers (SMs).”
> 
> ST 429-6 has no concept of SMs, so this document is not the right place for that requirement.

Yes.  I am intending to use text like:  "This method should not be used by implementations requiring FIPS certification."  I will leave out any reference to Security Manager.

**Comment by palemieux** [comment]
> "This method should not be used by implementations requiring FIPS certification." I will leave out any reference to Security Manager.

I do not think this is even necessary/useful. By removing the algorithm from the reference process, it becomes no longer required.

FIPS certification is required by the DCI spec, not SMPTE specs.

**Comment by dcbullock** [comment]
All makes sense to me.  Simple.

**Comment by jpviollet** [comment]
This makes sense to me too, thank you.
